spring.application.name=pena-plaza-portal

spring.datasource.url=jdbc:mysql://localhost:3306/pena_plaza?createDatabaseIfNotExist=true&serverTimezone=UTC&sslMode=DISABLED&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootroot

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration