CREATE TABLE users (
	id BIGINT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT uk_users_email UNIQUE (email)
);